### ISSUE TITLE
Packed and unpacked samples

### ISSUE THREAD

**Issue by nikhilh-20** [boozallen/MOTIF#1]
Hello, is there any information in the dataset that definitively tells me whether a particular sample is packed or unpacked? Or is it something that I have to analyze myself? Thanks!

**Comment by rjjoyce** [comment]
At the moment there is no indication of whether a file is packed or unpacked. Many of the articles we surveyed do include both packed and unpacked versions of malware samples, and both samples would be included in MOTIF. Furthermore, you can use some common heuristics (e.g file entropy) if you want to quickly find samples which are likely to be packed or unpacked.
