### ISSUE TITLE
Repeated sha1 and sha256 hashes in `motif_dataset.jsonl`

### ISSUE THREAD

**Issue by valakuzhyk** [boozallen/MOTIF#2]
Is there a reason that all of the `sha1` and `sha256` entries in motif_dataset.jsonl are the same?

**Comment by valakuzhyk** [comment]
#3 added a pull request to fix this apparent bug

**Comment by rjjoyce8** [comment]
Thank you for submitting the pull request, we've merged it into master. We appreciate the help!
